<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 08 Dec 2021 07:18:50 +0000
 */

$conf['title'] = 'My sitewiki';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>MzY2Nzg4OTk=';
