# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 08 Dec 2021 06:02:47 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$okmN6qb25ZgDen61lodkw.Oy72SQL85.oVnHS4Me9lIb8MjRwLvSW:lumwanga:kevinlumwanga7@gmail.com:admin,user
